### ISSUE TITLE
Test seems to fail on ubuntu docker image

### ISSUE THREAD

**Issue by chrisstuartparry** [aurora-multiphysics/aurora#42]
OS: Ubuntu 18.04 LTS (AWS EC2 Instance)

I've pulled the latest ubuntu docker image, and have successfully ran it.
I ran the following commands in the subsequent container:
```
cd /home/test/tests/thermal
../../../aurora-opt -i main.i
```
Instead of the expected behaviour (i.e. the test working), I get the following output:
```
../../../aurora-opt: error while loading shared libraries: libdagmc.so: cannot open shared object file: No such file or directory
```
I can confirm of course that the actual aurora-opt and main.i files do exist, in the correct directories.

I'm new to using Docker, and I have limited experience with OpenMC and MOOSE (less with OpenMC, more with MOOSE).

Thanks for your help! (And thanks for making such a tool!)

EDIT:

Nevermind, I managed to fix the problem by following the accepted answer from this [thread](https://stackoverflow.com/questions/480764/linux-error-while-loading-shared-libraries-cannot-open-shared-object-file-no-s) on stackoverflow. To repeat for redundancy and clarity, I did:
```
find / -name libdagmc.so
echo $LD_LIBRARY_PATH
LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/home/local/dagmc/lib/
export LD_LIBRARY_PATH
```
This then allowed `../../../aurora-opt -i main.i` to work from the correct test directory.

I also had an issue getting the test to run due to no cross-sections.xml file being found, but I fixed that by following the instructions in the Run Tests section of the README.md, that is doing
`export OPENMC_CROSS_SECTIONS=/PATH-TO-AURORA/aurora/data/endfb71_hdf5/cross_sections.xml`. I've repeated it here in case anyone else misses this (as it wasn't in the Docker section of the README.md).

**Comment by helen-brooks** [comment]
Hi! Glad you found a solution. This isn't in the documentation (perhaps it should be...) but all you had to do was run
```
source env/aurora_profile
```
to set up all the relevant environment variables inside the container.
The existences of the docker container is largely because it is is how I set up continuous integration, so it might not be the most user-friendly thing in the world!  Thank you so much for taking the time to raise the issue, it's great to have feedback from users and I'll make a note to update the README!
